// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_ from "./routes/[id].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $address_search from "./islands/address_search.tsx";
import * as $assessment_chart from "./islands/assessment_chart.tsx";
import * as $google_map from "./islands/google_map.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id].tsx": $_id_,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/address_search.tsx": $address_search,
    "./islands/assessment_chart.tsx": $assessment_chart,
    "./islands/google_map.tsx": $google_map,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
